### ISSUE TITLE
Backport to 1.20.1

### ISSUE THREAD

**Issue by NoaHimesaka1873** [ImplicitSaber/Forkcart#1]
I would like to use this mod for 1.20.1 (and also many would want to use it too due to its popularity) so I request for it to be ported to 1.20.1 if it's possible for you.

**Comment by ImplicitSaber** [comment]
I have just released [v1.20.1-1.1.0](https://github.com/ImplicitSaber/Forkcart/releases/tag/v1.20.1-1.1.0), which is a backport of the latest mod version to 1.20.1.

**Comment by NoaHimesaka1873** [comment]
One problem: it requires Java 21 not typically used for 1.20.1 environment. This also breaks compatibility with Sinytra Connector which expects Java 17 to work.

**Comment by NoaHimesaka1873** [comment]
CC: @ImplicitSaber

**Comment by ImplicitSaber** [comment]
I have just released v1.20.1-1.1.0-fix1. Java 17 should be used now.
